# Generated by Django 3.0.8 on 2021-01-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='update',
            new_name='updated',
        ),
    ]
